### ISSUE TITLE
update GDC to CCDH conversion.ipynb

### ISSUE THREAD

**Issue by turbomam** [cancerDHC/example-data#13]
`GDC to CCDH conversion.ipynb` does not currently run to completion.

- needs ccdh/ccdhmodel.py to be copied in from https://github.com/cancerDHC/example-data/pull/11
- needs to use string dumpers from linkml runtime

**Comment by gaurav** [comment]
This should be working now (as of PR #14). Could you please recheck when you have the time and make sure it's working for you? `pipenv run jupyter notebook` should work now.

**Comment by turbomam** [comment]
yes, the`GDC to CCDH conversion` notebook in branch `main` does run to completion as long as the local ccdh model is loaded as 

`from ccdh import ccdhmodel as ccdh`

but not from PyPI with

`import crdch_model.crdch_model as ccdh`

I think we're all aware of this now, so I'm closing the issue.
