### ISSUE TITLE
Figure out how to add demographic information to GDC head-and-mouth data

### ISSUE THREAD

**Issue by gaurav** [cancerDHC/example-data#24]
The GDC import doesn't include demographic information. We should modify the import at https://github.com/cancerDHC/example-data/blob/main/head-and-mouth/Head%20and%20Mouth%20Cancer%20Datasets.ipynb to include this information.

Related to #6.

**Comment by gaurav** [comment]
I have a suspicion that this might be as easy as modifying `"expand": "diagnoses,samples"` to `"expand": "diagnoses,samples,demographic"`, but it probably isn't that easy :)

**Comment by jooho-lee-kim** [comment]
It was easy like that.
Do we want to update gdc-head-and-mouth.json file to include demographic portion of data?

**Comment by gaurav** [comment]
Yes, please!
