### ISSUE TITLE
Convert "head and neck" Juypter Notebooks into an automated Python test suite

### ISSUE THREAD

**Issue by gaurav** [cancerDHC/example-data#8]
The [head-and-mouth](https://github.com/cancerDHC/example-data/tree/main/head-and-mouth) directory contains two datasets (one downloaded from GDC, and one downloaded from PDC) from cancers of the head and neck (not including the brain). This is the dataset we currently use in our [first GDC-to-CRDC-H transformation demonstration Jupyter Notebook](https://nbviewer.jupyter.org/github/cancerDHC/example-data/blob/main/GDC%20to%20CCDH%20conversion.ipynb). Some or all of this should be converted into a test suite, which can be used to test:
- [ ] That the Python Data Classes generated as part of the [CCDH model](https://github.com/cancerDHC/ccdhmodel/) can be loaded as a Python module, and further:
  - [ ] That entities, slots and enumerated values are documented.
  - [ ] That slots that should only take enumerated values throw errors if non-permitted values are used.
  - [ ] That entities can be exported as YAML and JSON-LD.
- [ ] That the JSON-LD exported from Python Data Classes can be successfully converted into Turtle.
- [ ] That the Turtle generated from the generated JSON-LD passes validation with the ShEx shapes generated in the CCDH model.

I'm not sure if we need to convert the [Head and Mouth Cancer Datasets download notebook](https://github.com/cancerDHC/example-data/blob/main/head-and-mouth/Head%20and%20Mouth%20Cancer%20Datasets.ipynb) with you as well -- it might be useful to always use the most up-to-date data, or it might just be confusing if we run into problems with the PDC/GDC APIs. I'm inclined to leave them out for now.

**Comment by turbomam** [comment]
I may not be able to do all of this on my own

**Comment by gaurav** [comment]
@turbomam No worries! Which parts would you like to focus on?

**Comment by turbomam** [comment]
- I'm trying to build my own linkml repo from the template.
- Then I'd like to run your existing notebooks
- Then I'll be able to answer your "which parts" question better. 
- 
Is that OK?

**Comment by gaurav** [comment]
Sounds like a plan! 👍🏾

**Comment by gaurav** [comment]
@turbomam Do you have any changes to the Jupyter Notebook you'd like to commit? If not, I'll come up with a PR early next week that applies all the fixes we've discussed on Slack, and then you can keep working on that.

**Comment by turbomam** [comment]
@gaurav No I don't think I have anything to commit outside of what we've already discussed. Thanks.
